project:
  type: website
  output-dir: docs

website:
  title: "Corpus analysis (Variant 1)"
  navbar:
    left:
      - href: index.qmd
        text: Report

format:
  html:
    toc: true
    code-fold: true
    theme: cosmo
